### ISSUE TITLE
Error Inflating by android:scaleType="fitXY" 

### ISSUE THREAD

**Issue by rtugeek** [hdodenhof/CircleImageView#116]
```
        <de.hdodenhof.circleimageview.CircleImageView
            android:id="@+id/iv_avatar"
            android:layout_width="@dimen/base_scrollview_top_height"
            android:layout_height="@dimen/base_scrollview_top_height"
            android:layout_alignParentLeft="true"
            android:layout_alignParentTop="true"
            android:layout_marginLeft="@dimen/margin_chat_top"
            android:src="@drawable/avatar"
            android:scaleType="fitXY" />
```

Here is the logcat:

```
  android.view.InflateException: Binary XML file line #20: Error inflating class <unknown>
at android.view.LayoutInflater.createView(LayoutInflater.java:633)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
```

It works fine when I remove this line ` android:scaleType="fitXY" `

**Comment by hdodenhof** [comment]
This is by design, only CENTER_CROP is supported (see the "Limitations" section in the readme).
