### ISSUE TITLE
Class not found error

### ISSUE THREAD

**Issue by kamalsint** [hdodenhof/CircleImageView#123]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.medi.trustmedi/com.medi.trustmedi.activity.MapDashBoardActivity}: android.view.InflateException: Binary XML file line #26: Error inflating class de.hdodenhof.circleimageview.CircleImageView
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349)
      at android.app.ActivityThread.access$700(ActivityThread.java:159)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
      at android.os.Handler.dispatchMessage(Handler.java:99)
      at android.os.Looper.loop(Looper.java:176)
      at android.app.ActivityThread.main(ActivityThread.java:5419)
      at java.lang.reflect.Method.invokeNative(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:525)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
      at dalvik.system.NativeStart.main(Native Method)
   Caused by: android.view.InflateException: Binary XML file line #26: Error inflating class de.hdodenhof.circleimageview.CircleImageView
      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
      at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
      at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
      at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
      at android.support.design.internal.NavigationMenuPresenter.inflateHeaderView(NavigationMenuPresenter.java:189)
      at android.support.design.widget.NavigationView.inflateHeaderView(NavigationView.java:262)
      at com.medi.trustmedi.activity.MapDashBoardActivity.initializeView(MapDashBoardActivity.java:279)
      at com.medi.trustmedi.activity.MapDashBoardActivity.onCreate(MapDashBoardActivity.java:190)
      at android.app.Activity.performCreate(Activity.java:5372)
      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2257)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349) 
      at android.app.ActivityThread.access$700(ActivityThread.java:159) 
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
      at android.os.Handler.dispatchMessage(Handler.java:99) 
      at android.os.Looper.loop(Looper.java:176) 
      at android.app.ActivityThread.main(ActivityThread.java:5419) 
      at java.lang.reflect.Method.invokeNative(Native Method) 
      at java.lang.reflect.Method.invoke(Method.java:525) 
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862) 
      at dalvik.system.NativeStart.main(Native Method) 
   Caused by: java.lang.ClassNotFoundException: Didn't find class "de.hdodenhof.circleimageview.CircleImageView" on path: /data/app/com.medi.trustmedi-2.apk
      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:64)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
      at android.view.LayoutInflater.createView(LayoutInflater.java:565)
      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
      at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
      at android.view.LayoutInflater.inflate(LayoutInflater.java:498) 
      at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
      at android.support.design.internal.NavigationMenuPresenter.inflateHeaderView(NavigationMenuPresenter.java:189) 
      at android.support.design.widget.NavigationView.inflateHeaderView(NavigationView.java:262) 
      at com.medi.trustmedi.activity.MapDashBoardActivity.initializeView(MapDashBoardActivity.java:279) 
      at com.medi.trustmedi.activity.MapDashBoardActivity.onCreate(MapDashBoardActivity.java:190) 
      at android.app.Activity.performCreate(Activity.java:5372) 
      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104) 
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2257) 
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349) 
      at android.app.ActivityThread.access$700(ActivityThread.java:159) 
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
      at android.os.Handler.dispatchMessage(Handler.java:99) 
      at android.os.Looper.loop(Looper.java:176) 
      at android.app.ActivityThread.main(ActivityThread.java:5419) 
      at java.lang.reflect.Method.invokeNative(Native Method) 
      at java.lang.reflect.Method.invoke(Method.java:525) 
```

app: build.gradle file

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "com.medi.trustmedi"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0.1"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        packagingOptions {
            exclude 'META-INF/DEPENDENCIES'
            exclude 'META-INF/NOTICE'
            exclude 'META-INF/LICENSE'
        }
    }

    dexOptions {
        javaMaxHeapSize "4g"
    }
//    useLibrary 'org.apache.http.legacy'
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'org.apache.httpcomponents:httpclient:jar:4.5.1'
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.android.support:support-v4:23.3.0'
    compile 'com.android.support:design:23.3.0'
    compile 'com.google.android.gms:play-services:8.4.0'
    compile 'org.apache.httpcomponents:httpcore:4.3.2'
    compile 'org.apache.httpcomponents:httpmime:4.3.5'
    compile 'com.oguzdev:CircularFloatingActionMenu:1.0.2'
    compile 'com.android.support:multidex:1.0.0'
    compile 'com.google.android.gms:play-services-ads:8.4.0'
    compile 'com.google.android.gms:play-services-identity:8.4.0'
    compile 'com.google.android.gms:play-services-gcm:8.4.0'
    compile 'com.android.support:cardview-v7:23.3.0'
    compile 'com.android.support:recyclerview-v7:23.3.0'
//    compile 'com.pkmmte.view:circularimageview:1.1'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.wunderlist:sliding-layer:1.2.5'
    compile 'com.google.android.gms:play-services-auth:8.4.0'
    compile 'de.hdodenhof:circleimageview:2.0.0'
//    compile 'com.github.hdodenhof:CircleImageView:v2.0.0'
}
```

Project: build.gradle file

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

This is my issue, kindly help me out.

Thanks in advance.

**Comment by hdodenhof** [comment]
This seems related to MutliDex. Do you properly install MultiDex in your application class?

**Comment by kamalsint** [comment]
Yes i have installed multidex properly. I think there is some problem with the lib versions in dependencies.

**Comment by hdodenhof** [comment]
I can't see an obvious one. Does your app work if you completely remove this lib and leave everything else as is?

**Comment by kamalsint** [comment]
Hi, this lib works perfectly well when i changed the version of the other dependencies as it is below.

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'org.apache.httpcomponents:httpclient:jar:4.5.1'
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'
    compile 'com.android.support:appcompat-v7:23.0.0-alpha1'
    compile 'com.android.support:support-v4:23.0.0-alpha1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.google.android.gms:play-services:8.4.0'
    compile 'org.apache.httpcomponents:httpcore:4.3.2'
    compile 'org.apache.httpcomponents:httpmime:4.3.5'
    compile 'com.oguzdev:CircularFloatingActionMenu:1.0.2'
    compile 'com.android.support:multidex:1.0.0'
    compile 'com.google.android.gms:play-services-ads:8.4.0'
    compile 'com.google.android.gms:play-services-identity:8.4.0'
    compile 'com.google.android.gms:play-services-gcm:8.4.0'
    compile 'com.android.support:cardview-v7:23.0.+'
    compile 'com.android.support:recyclerview-v7:23.0.+'
//    compile 'com.pkmmte.view:circularimageview:1.1'
//    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.wunderlist:sliding-layer:1.2.5'
    compile 'com.google.android.gms:play-services-auth:8.4.0'
    compile 'de.hdodenhof:circleimageview:2.0.0'
}



I think the problem was with the different version of other libs. Might be some incompatibility issue with other lib.

**Comment by hdodenhof** [comment]
I guess this has resolved itself by now.

**Comment by DeveloperYasir** [comment]
this library is not working in android jellybean.. i have tested it various jellybeans but all i get the same error..
