### ISSUE TITLE
TextDrawable's drawable is not working with CircleImageView

### ISSUE THREAD

**Issue by MarcinOrlowski** [hdodenhof/CircleImageView#129]
There's something not working when CircleImageView is fed by Drawable produced with use of TextDrawable library https://github.com/amulyakhare/TextDrawable - when I replace working ImageView with CircleImageView I see this in log:

    java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
        at de.hdodenhof.circleimageview.CircleImageView.getBitmapFromDrawable(CircleImageView.java:253)
        at de.hdodenhof.circleimageview.CircleImageView.setImageDrawable(CircleImageView.java:209)
        at pl.neo.ui.GlideHelper.load(GlideHelper.java:146)
        at pl.neo.ui.BindingHelper.handleThumbnail(BindingHelper.java:68)
        at pl.neo.databinding.EmailMapGridItemBinding.executeBindings(EmailMapGridItemBinding.java:120)
        at android.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:355)
        at android.databinding.ViewDataBinding$6.run(ViewDataBinding.java:172)
        at android.databinding.ViewDataBinding$7.doFrame(ViewDataBinding.java:238)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
        at android.view.Choreographer.doFrame(Choreographer.java:549)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by hdodenhof** [comment]
This is probably because `TextDrawable` has no intrinsic width and height - these kind of drawables are currently not supported.

**Comment by MarcinOrlowski** [comment]
Ok. It seems the project got many actively developed forks so I will check these instead. Thanks for info.

**Comment by hdodenhof** [comment]
You could also work around the issue by giving the `TextDrawable` a fixed sized using its builder:
```
TextDrawable.builder()
    .beginConfig()
        .width(60)
        .height(60)
    .endConfig()
    [..]
```
While this could work, I wouldn't recommend it. The underlying mechanism used for creating a cicular shape here is really efficient for bitmaps, not so much for other kinds of drawables. Using the native option for circular tiles would be a better solution.
```
TextDrawable.builder()
    [..]
    .buildRound("A", Color.RED)
```

**Comment by MarcinOrlowski** [comment]
Thanks. I used config thing, with width, height being read from the target ImageView instead of being hardcoded:

        .width(targetImageView.getWidth())
        .height(targetImageView.getHeight())

and this solves my problem here. I did not want to use `buildRound()` for code consistency (I do not like unnecessary "special cases" in the code). Thanks.
