### ISSUE TITLE
Does this work with activity transition on Lollipop and above?

### ISSUE THREAD

**Issue by anhhnguyen206** [hdodenhof/CircleImageView#136]
I received a crash when attempted to:

```
java.lang.IllegalArgumentException: ScaleType FIT_CENTER not supported.
        at de.hdodenhof.circleimageview.CircleImageView.setScaleType(CircleImageView.java:105)
        at android.app.ActivityTransitionCoordinator.setSharedElementState(ActivityTransitionCoordinator.java:431)
        at android.app.ActivityTransitionCoordinator.setSharedElementState(ActivityTransitionCoordinator.java:545)
        at android.app.EnterTransitionCoordinator.startSharedElementTransition(EnterTransitionCoordinator.java:329)
        at android.app.EnterTransitionCoordinator.-wrap4(EnterTransitionCoordinator.java)
        at android.app.EnterTransitionCoordinator$5$1$1.run(EnterTransitionCoordinator.java:399)
        at android.app.ActivityTransitionCoordinator.startTransition(ActivityTransitionCoordinator.java:773)
        at android.app.EnterTransitionCoordinator$5$1.onPreDraw(EnterTransitionCoordinator.java:396)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2055)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
        at android.view.Choreographer.doFrame(Choreographer.java:606)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

Seems like the activity transition framework trying to set the ScaleType to FIT_CENTER which apparently not support by CircleImageView.  Is there any workaround?

**Comment by hdodenhof** [comment]
I just had a quick look at how the transition framework works and I think it should actually work with a CircleImageView - but I've to dig a little deeper to confirm. Could you provide the relevant parts of your code for investigation?

**Comment by anhhnguyen206** [comment]
Thanks for your reply @hdodenhof. 

I will create a simple application to test this out and get back to you on this in a day or two.

**Comment by gnumilanix** [comment]
Apparently in my case, it was my mistake. It happened when view did not match the "transitionName" to that of the view that was being transitioned:

`ActivityOptionsCompat.makeSceneTransitionAnimation(getActivity(), fl,"civ_trans");`

`        <de.hdodenhof.circleimageview.CircleImageView
            android:id="@+id/civ"
            android:transitionName="civ_trans"
            app:civ_border_color="@color/colorTextGrey400"
            app:civ_border_width="2dp"/>

      <FrameLayout
            android:id="@+id/fl"
            android:transitionName="fl_trans"
            app:civ_border_color="@color/colorTextGrey400"
            app:civ_border_width="2dp"/>`

This apparently should not be an issue for following case:
`ActivityOptionsCompat.makeSceneTransitionAnimation(getActivity(), civ,"civ_trans");`

**Comment by VapeNaysh420blzit** [comment]
Hello, I did a workaround. Hope you'll like it. 

**<RelativeLayout
    android:layout_width="wrap_content"
    android:layout_height="120dp"
    android:transitionName="civ_shared_element"
    android:layout_gravity="center">

            <de.hdodenhof.circleimageview.CircleImageView
                xmlns:app="http://schemas.android.com/apk/res-auto"
                android:id="@+id/imgProfilePicture"
                android:layout_width="120dp"
                android:layout_height="120dp"
                android:layout_gravity="center"
                app:civ_border_width="2dp"
                app:civ_border_color="#FF000000" />


</RelativeLayout>**

**Comment by VapeNaysh420blzit** [comment]
Hello, I did a work around. Hope you'll like it.

``**<RelativeLayout
    android:layout_width="wrap_content"
    android:layout_height="120dp"
    android:transitionName="civ_shared_element"
    android:layout_gravity="center">

            <de.hdodenhof.circleimageview.CircleImageView
                xmlns:app="http://schemas.android.com/apk/res-auto"
                android:id="@+id/imgProfilePicture"
                android:layout_width="120dp"
                android:layout_height="120dp"
                android:layout_gravity="center"
                app:civ_border_width="2dp"
                app:civ_border_color="#FF000000" />


</RelativeLayout>**``

**Comment by VapeNaysh420blzit** [comment]
Hello, I did a workaround, Hope you'll like it.

`<RelativeLayout
    android:layout_width="wrap_content"
    android:layout_height="120dp"
    android:transitionName="civ_shared_element"
    android:layout_gravity="center">

            <de.hdodenhof.circleimageview.CircleImageView
                xmlns:app="http://schemas.android.com/apk/res-auto"
                android:id="@+id/imgProfilePicture"
                android:layout_width="120dp"
                android:layout_height="120dp"
                android:layout_gravity="center"
                app:civ_border_width="2dp"
                app:civ_border_color="#FF000000" />


</RelativeLayout>`

**Comment by VapeNaysh420blzit** [comment]
Hello, I did a workaround. Hope you'll like it.

[layout.txt](https://github.com/hdodenhof/CircleImageView/files/998146/layout.txt)

Just set the "android:transitionName" in a another layout. e.g: <RelativeLayout>

**Comment by rkoshti** [comment]
@VapeNaysh420blzit its working with another layout .

**Comment by costelo01** [comment]
^Yes it would work with another layout, but if you nested the imageview inside it, the "relative layout" or etc, will work as a parent as to the child (imageview). Get rid of the height and width of the imageview to force use the parent's width_height layout. Cheers!
