### ISSUE TITLE
viewSub.inflate threw the exception

### ISSUE THREAD

**Issue by fansfans** [hdodenhof/CircleImageView#146]
AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.cxp.interview, PID: 6778
                                                                 android.view.InflateException: Binary XML file line #20: Error inflating class com.core.corelib.ui.widget.CircleImageView
                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:640)
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:775)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:778)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:778)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:512)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:409)
                                                                     at android.view.ViewStub.inflate(ViewStub.java:259)
                                                                     at com.core.corelib.ui.GlobalBaseFragment2.onCreateView(GlobalBaseFragment2.java:52)
                                                                     at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                                     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
                                                                     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                                     at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
                                                                     at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:164)
                                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
                                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
                                                                     at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
                                                                     at android.view.View.measure(View.java:16543)
                                                                     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
                                                                     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
                                                                     at android.view.View.measure(View.java:16543)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5147)
                                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1430)
                                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:716)
                                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:609)
                                                                     at android.view.View.measure(View.java:16543)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5147)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                     at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                     at android.view.View.measure(View.java:16543)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5147)
                                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1430)
                                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:716)
                                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:609)
                                                                     at android.view.View.measure(View.java:16543)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5147)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                     at android.view.View.measure(View.java:16543)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5147)
                                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1430)
                                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:716)
                                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:609)
                                                                     at android.view.View.measure(View.java:16543)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5147)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                     at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2327)
                                                                     at android.view.View.measure(View.java:16543)
                                                                     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1979)
                                                                     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1140)
                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1331)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1027)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5884)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:780)
                                                                    at android.view.Choreographer.doCallback

**Comment by hdodenhof** [comment]
You are using `com.core.corelib.ui.widget.CircleImageView` - that's not this library.
