### ISSUE TITLE
not working on API 19

### ISSUE THREAD

**Issue by limaneto** [hdodenhof/CircleImageView#149]
My app works fine in API's newer than 19, but in API 19 gives this error.

```
FATAL EXCEPTION: main
Process: com.voidapp.android.voidapp, PID: 7323
android.view.InflateException: Binary XML file line #9: Error inflating class de.hdodenhof.circleimageview.CircleImageView
      at android.view.LayoutInflater.createView(LayoutInflater.java:621)
      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697)
      at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)
      at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
      at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
      at com.voidapp.android.voidapp.Views.Adapters.MyItemRecyclerViewAdapter.onCreateViewHolder(MyItemRecyclerViewAdapter.java:34)
      at com.voidapp.android.voidapp.Views.Adapters.MyItemRecyclerViewAdapter.onCreateViewHolder(MyItemRecyclerViewAdapter.java:20)
      at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5779)
      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5003)
      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
      at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
      at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
      at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
      at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
      at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3260)
      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3069)
      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3518)
      at android.view.View.layout(View.java:14817)
      at android.view.ViewGroup.layout(ViewGroup.java:4631)
      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
      at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
      at android.view.View.layout(View.java:14817)
      at android.view.ViewGroup.layout(ViewGroup.java:4631)
      at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:120)
      at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
      at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1319)
      at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:815)
      at android.view.View.layout(View.java:14817)
      at android.view.ViewGroup.layout(ViewGroup.java:4631)
      at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1191)
      at android.view.View.layout(View.java:14817)
      at android.view.ViewGroup.layout(ViewGroup.java:4631)
      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
      at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
      at android.view.View.layout(View.java:14817)
      at android.view.ViewGroup.layout(ViewGroup.java:4631)
      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
      at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
      at android.view.View.layout(View.java:14817)
      at android.view.ViewGroup.layout(ViewGroup.java:4631)
      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
      at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
      at android.view.View.layout(View.java:14817)
      at android.view.ViewGroup.layout(ViewGroup.java:4631)
      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
      at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
      at android.view.View.layout(View.java:14817)
      at android.view.ViewGroup.layout(ViewGroup.java:4631)
      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
      at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
      at android.view.View.layout(View.java:14817)
      at android.view.ViewGroup.layout
```

**Comment by hdodenhof** [comment]
Please post the full stack trace, the relevant parts are missing.

**Comment by limaneto** [comment]
<de.hdodenhof.circleimageview.CircleImageView
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/profile_image"
        android:layout_width="45dp"
        android:layout_height="45dp"
        android:layout_gravity="center_vertical"
        android:src="@drawable/neto"
        app:civ_border_width="0dp"
        app:civ_border_color="#FF000000"/>


<img width="1646" alt="screen shot 2016-08-07 at 13 41 18" src="https://cloud.githubusercontent.com/assets/6009780/17463799/b7bcb4de-5ca4-11e6-8afe-1e5ef4e87e2a.png">
 the error msg stops righ there, I dont know why

**Comment by hdodenhof** [comment]
It's impossible to say without the full stack trace, but I suspect this to be an incomplete setup of Multidex, please have a look at #96.

As adb seems to truncate the logcat output you'll have to debug the view inflation to find the root cause of the `InflateException`.

**Comment by limaneto** [comment]
I was selecting a JPEG image and putting directly on Drawable folder, when I converted the image to PNG it worked.
