### ISSUE TITLE
java.lang.IllegalArgumentException: width and height must be > 0 error line at onDestroy

### ISSUE THREAD

**Issue by virengujariya** [hdodenhof/CircleImageView#181]
java.lang.IllegalArgumentException: width and height must be > 0 on Activity `onDestroy` method

Is there anything I am missing?

**Comment by hdodenhof** [comment]
It's impossible to say what's going on without a little more details about your setup. How does your app interact with this library?

**Comment by virengujariya** [comment]
@hdodenhof  ```Glide.with(context).load(url)
                .dontAnimate()
                .placeholder(R.drawable.image_placeholder)
                .error(R.drawable.image_error)
                .into(circleImageView);```

And 

```<de.hdodenhof.circleimageview.CircleImageView
            android:id="@+id/imageview_profile"
            android:layout_width="@dimen/social_profile_avatar_40"
            android:layout_height="@dimen/social_profile_avatar_40"
            android:layout_centerVertical="true"
            android:layout_marginLeft="@dimen/horizontal_margin_left" />```

**Comment by virengujariya** [comment]
It is not crashing the app but I get following log 

```java.lang.IllegalArgumentException: width and height must be > 0
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at android.graphics.Bitmap.createBitmap(Bitmap.java:933)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at android.graphics.Bitmap.createBitmap(Bitmap.java:912)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at de.hdodenhof.circleimageview.CircleImageView.getBitmapFromDrawable(CircleImageView.java:337)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at de.hdodenhof.circleimageview.CircleImageView.initializeBitmap(CircleImageView.java:354)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at de.hdodenhof.circleimageview.CircleImageView.setImageDrawable(CircleImageView.java:285)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at com.bumptech.glide.request.target.ImageViewTarget.onLoadCleared(ImageViewTarget.java:70)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at com.bumptech.glide.request.GenericRequest.clear(GenericRequest.java:323)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at com.bumptech.glide.GenericRequestBuilder.into(GenericRequestBuilder.java:653)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at com.bumptech.glide.GenericRequestBuilder.into(GenericRequestBuilder.java:697)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at com.bumptech.glide.DrawableRequestBuilder.into(DrawableRequestBuilder.java:448)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at me.latergram.latergramme.helpers.GlideHelper.loadProfile(GlideHelper.java:171)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at me.latergram.latergramme.helpers.GlideHelper.loadProfile(GlideHelper.java:175)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at me.latergram.latergramme.adapters.SearchPeopleResultsAdaptor.bindView(SearchPeopleResultsAdaptor.java:30)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at android.support.v4.widget.CursorAdapter.getView(CursorAdapter.java:273)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at android.widget.AbsListView.obtainView(AbsListView.java:2823)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at android.widget.ListPopupWindow$DropDownListView.obtainView(ListPopupWindow.java:1694)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at android.widget.ListView.measureHeightOfChildren(ListView.java:1290)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at android.widget.ListPopupWindow.buildDropDown(ListPopupWindow.java:1191)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at android.widget.ListPopupWindow.show(ListPopupWindow.java:578)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at android.widget.AutoCompleteTextView.showDropDown(AutoCompleteTextView.java:1110)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at android.widget.AutoCompleteTextView.updateDropDownForFilter(AutoCompleteTextView.java:984)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at android.widget.AutoCompleteTextView.onFilterComplete(AutoCompleteTextView.java:966)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:285)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at android.os.Looper.loop(Looper.java:145)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5942)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
03-14 14:15:14.211 23415-23415/me.latergram.latergramme W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)```

**Comment by hdodenhof** [comment]
Does it still happen if you remove the placeholder?

**Comment by hdodenhof** [comment]
Your assumption is right. A possible fix would be using a color drawable instead:
```
<color xmlns:android="http://schemas.android.com/apk/res/android"
       android:color="@color/grey200"/>
```

**Comment by rickbijkerk** [comment]
Ihave this same problem is it perhaps an idea to use the drawable's bounds width/height if the drawables intrinsicHeight/width are <=0

This is what it looks like now in the getBitmapFromDrawable function

bitmap = Bitmap.createBitmap(drawable.getIntrinsicWidth(), drawable.getIntrinsicHeight(), BITMAP_CONFIG);

**Comment by hdodenhof** [comment]
Original issue has been resolved.
