### ISSUE TITLE
facing lots of java.lang.OutOfMemoryError randomly

### ISSUE THREAD

**Issue by shakeri-mreza** [hdodenhof/CircleImageView#187]
sometimes I get this error when I use a circleImageView in an activity. nothing special. it just happens randomly.
why is that?? this caused serious problems for me! 
any idea?

java.lang.OutOfMemoryError: Failed to allocate a 12531612 byte allocation with 10639656 free bytes and 10MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:827)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:646)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1019)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:3778)
	at android.content.res.Resources.loadDrawable(Resources.java:3651)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:762)
	at android.widget.ImageView.<init>(ImageView.java:151)
	at android.widget.ImageView.<init>(ImageView.java:140)
	at de.hdodenhof.circleimageview.CircleImageView.<init>(CircleImageView.java:89)
	at de.hdodenhof.circleimageview.CircleImageView.<init>(CircleImageView.java:85)

**Comment by hdodenhof** [comment]
Well, that's a classic `OutOfMemoryError`, not related to this library. From the stack trace you can see that it happens during initialization of `ImageView`. The `Drawable` you are trying to load is just to big for the device to handle.
