### ISSUE TITLE
OutOfMemoryError when passing a GlideDrawable

### ISSUE THREAD

**Issue by anthony-cannon** [hdodenhof/CircleImageView#195]
I am using Glide to set my ImageView and i am getting this error every so often...

```
java.lang.OutOfMemoryError: Failed to allocate a 48771084 byte allocation with 16777216 free bytes and 33MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:977)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:948)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:915)
	at de.hdodenhof.circleimageview.CircleImageView.getBitmapFromDrawable(CircleImageView.java:337)
	at de.hdodenhof.circleimageview.CircleImageView.initializeBitmap(CircleImageView.java:354)
	at de.hdodenhof.circleimageview.CircleImageView.setImageDrawable(CircleImageView.java:285)
	at com.goevo.android.util.ViewUtil$2.onResourceReady(ViewUtil.java:73)
	at com.goevo.android.util.ViewUtil$2.onResourceReady(ViewUtil.java:70)
	at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:525)
	at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:507)
	at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:158)
	at com.bumptech.glide.load.engine.EngineJob.access$100(EngineJob.java:22)
	at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:202)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6688)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by anthony-cannon** [comment]
Do you know why this is happening? or do you need more information?

**Comment by hdodenhof** [comment]
Well, that's an easy one: you are trying to load a huge image whose size (~49MB) exceeds the available memory. You need to scale it before supplying it to `CircleImageView`.
