### ISSUE TITLE
do not  support 4.4？

### ISSUE THREAD

**Issue by 287138531** [hdodenhof/CircleImageView#213]
Caused by: java.lang.NoClassDefFoundError: de.hdodenhof.circleimageview.R$styleable
                                                                       at de.hdodenhof.circleimageview.CircleImageView.<init>(CircleImageView.java:91)
                                                                       at de.hdodenhof.circleimageview.CircleImageView.<init>(CircleImageView.java:85)

**Comment by hdodenhof** [comment]
4.4 is supported. This is likely an issue with your multidex setup, make sure to properly include the multidex support library.

**Comment by 287138531** [comment]
you right 。 I  resolved。 tks

**Comment by reverie-ss** [comment]
I too had the same problem. Thanks @hdodenhof for the solution
