### ISSUE TITLE
so easy OutOfMemoryError ! please help me!

### ISSUE THREAD

**Issue by hudan2714** [hdodenhof/CircleImageView#237]
```
java.lang.OutOfMemoryError
         at android.graphics.Bitmap.nativeCreate(Native Method)
         at android.graphics.Bitmap.createBitmap(Bitmap.java:726)
         at android.graphics.Bitmap.createBitmap(Bitmap.java:703)
         at android.graphics.Bitmap.createBitmap(Bitmap.java:670)
         at de.hdodenhof.circleimageview.CircleImageView.getBitmapFromDrawable(CircleImageView.java:367)
         at de.hdodenhof.circleimageview.CircleImageView.initializeBitmap(CircleImageView.java:384)
         at de.hdodenhof.circleimageview.CircleImageView.setImageDrawable(CircleImageView.java:315)
         at com.bumptech.glide.request.target.GlideDrawableImageViewTarget.setResource(GlideDrawableImageViewTarget.java:80)
         at com.bumptech.glide.request.target.GlideDrawableImageViewTarget.setResource(GlideDrawableImageViewTarget.java:12)
         at com.bumptech.glide.request.target.ImageViewTarget.onResourceReady(ImageViewTarget.java:76)
         at com.bumptech.glide.request.target.GlideDrawableImageViewTarget.onResourceReady(GlideDrawableImageViewTarget.java:66)
         at com.bumptech.glide.request.target.GlideDrawableImageViewTarget.onResourceReady(GlideDrawableImageViewTarget.java:12)
         at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:525)
         at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:507)
         at com.bumptech.glide.load.engine.Engine.load(Engine.java:164)
         at com.bumptech.glide.request.GenericRequest.onSizeReady(GenericRequest.java:449)
         at com.bumptech.glide.request.GenericRequest.begin(GenericRequest.java:270)
         at com.bumptech.glide.manager.RequestTracker.runRequest(RequestTracker.java:37)
         at com.bumptech.glide.GenericRequestBuilder.into(GenericRequestBuilder.java:661)
         at com.bumptech.glide.GenericRequestBuilder.into(GenericRequestBuilder.java:697)
         at com.bumptech.glide.DrawableRequestBuilder.into(DrawableRequestBuilder.java:448)
```

**Comment by cbedoy** [comment]
Maybe is releated with Glide

**Comment by vasskob** [comment]
I have the same issue.

**Comment by jagtejsodhi** [comment]
I have the same issue. I've tried scaling the image before passing it into CircleImageView but still see the problem. @hudan2714 any luck with a solution?

**Comment by vasskob** [comment]
Seems that it's not a Glide or CircleImageView problem, but not sure.  Just add to the application in manifest this attribute.  android:largeHeap="true"

**Comment by jagtejsodhi** [comment]
@vasskob I already did that, still seeing OOM crash.

**Comment by cbedoy** [comment]
@hudan2714  do you have the image's link?

**Comment by andreynovikov** [comment]
I used this approach: https://stackoverflow.com/a/10127787/488489 and it helped.

**Comment by hdodenhof** [comment]
The SO answer is quite comprehensive and should help solve this.
