### ISSUE TITLE
on android 7.0 ,there is a problem with new glide verison 4.3.1

### ISSUE THREAD

**Issue by yanzhendong** [hdodenhof/CircleImageView#242]
```
java.lang.IllegalStateException: Software rendering doesn't support hardware bitmaps
11-13 18:24:37.461 32110-32110/com.cylan.doby W/System.err:     at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:532)
11-13 18:24:37.461 32110-32110/com.cylan.doby W/System.err:     at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:62)
11-13 18:24:37.461 32110-32110/com.cylan.doby W/System.err:     at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:120)
11-13 18:24:37.461 32110-32110/com.cylan.doby W/System.err:     at android.graphics.Canvas.drawBitmap(Canvas.java:1434)
11-13 18:24:37.461 32110-32110/com.cylan.doby W/System.err:     at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
11-13 18:24:37.461 32110-32110/com.cylan.doby W/System.err:     at com.cylan.jiafeigou.support.photoselect.CircleImageView.getBitmapFromDrawable(CircleImageView.java:362)
11-13 18:24:37.461 32110-32110/com.cylan.doby W/System.err:     at com.cylan.jiafeigou.support.photoselect.CircleImageView.initializeBitmap(CircleImageView.java:374)
11-13 18:24:37.461 32110-32110/com.cylan.doby W/System.err:     at com.cylan.jiafeigou.support.photoselect.CircleImageView.setImageDrawable(CircleImageView.java:305)
11-13 18:24:37.461 32110-32110/com.cylan.doby W/System.err:     at com.bumptech.glide.request.target.DrawableImageViewTarget.setResource(DrawableImageViewTarget.java:22)
11-13 18:24:37.461 32110-32110/com.cylan.doby W/System.err:     at com.bumptech.glide.request.target.DrawableImageViewTarget.setResource(DrawableImageViewTarget.java:10)
11-13 18:24:37.461 32110-32110/com.cylan.doby W/System.err:     at com.bumptech.glide.request.target.ImageViewTarget.setResourceInternal(ImageViewTarget.java:116)
11-13 18:24:37.461 32110-32110/com.cylan.doby W/System.err:     at com.bumptech.glide.request.target.ImageViewTarget.onResourceReady(ImageViewTarget.java:93)
11-13 18:24:37.461 32110-32110/com.cylan.doby W/System.err:     at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:560)
11-13 18:24:37.461 32110-32110/com.cylan.doby W/System.err:     at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:530)
11-13 18:24:37.461 32110-32110/com.cylan.doby W/System.err:     at com.bumptech.glide.load.engine.Engine.load(Engine.java:183)
11-13 18:24:37.461 32110-32110/com.cylan.doby W/System.err:     at com.bumptech.glide.request.SingleRequest.onSizeReady(SingleRequest.java:443)
11-13 18:24:37.461 32110-32110/com.cylan.doby W/System.err:     at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.getSize(ViewTarget.java:250)
11-13 18:24:37.461 32110-32110/com.cylan.doby W/System.err:     at com.bumptech.glide.request.target.ViewTarget.getSize(ViewTarget.java:89)
11-13 18:24:37.461 32110-32110/com.cylan.doby W/System.err:     at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:257)
11-13 18:24:37.461 32110-32110/com.cylan.doby W/System.err:     at com.bumptech.glide.manager.RequestTracker.runRequest(RequestTracker.java:39)
11-13 18:24:37.461 32110-32110/com.cylan.doby W/System.err:     at com.bumptech.glide.RequestManager.track(RequestManager.java:473)
11-13 18:24:37.461 32110-32110/com.cylan.doby W/System.err:     at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:576)
11-13 18:24:37.462 32110-32110/com.cylan.doby W/System.err:     at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:626)
```

**Comment by hdodenhof** [comment]
That's a Glide / Android framework issue, unrelated to this library. Please have a look at [this](http://bumptech.github.io/glide/doc/hardwarebitmaps.html#whats-broken-when-we-use-hardware-bitmaps).
