### ISSUE TITLE
Getting Problem in CircleImageView in Recyclerview

### ISSUE THREAD

**Issue by kundavarapuSubrahmanyaChari** [hdodenhof/CircleImageView#251]
<de.hdodenhof.circleimageview.CircleImageView
                    android:layout_width="@dimen/advt_image_height"
                    android:layout_height="@dimen/advt_image_height"
                    android:src="@drawable/profile_dpic_60"
                    android:contentDescription="@string/Mycart_image_descriiption"
                    android:scaleType="fitXY"
                    android:id="@+id/product_order_image"
                    app:civ_border_width="2dp"
                    app:civ_border_color="@color/accent"/>

FATAL EXCEPTION: main
                                                                              Process: com.latestone.retail_app.uat, PID: 22978
                                                                              android.view.InflateException: Binary XML file line #82: Binary XML file line #82: Error inflating class de.hdodenhof.circleimageview.CircleImageView
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
                                                                                  at com.latestone.retail_app.profile.OrderHistory$OrderHistoryRecycleAdapter.onCreateViewHolder(OrderHistory.java:236)
                                                                                  at com.latestone.retail_app.profile.OrderHistory$OrderHistoryRecycleAdapter.onCreateViewHolder(OrderHistory.java:225)
                                                                                  at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5779)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5003)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
                                                                                  at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                                                  at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                                                                                  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                                  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                                  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3260)
                                                                                  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3069)
                                                                                  at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3518)
                                                                                  at android.view.View.layout(View.java:17995)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                  at android.view.View.layout(View.java:17995)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                  at android.view.View.layout(View.java:17995)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                  at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
                                                                                  at android.view.View.layout(View.java:17995)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                  at android.view.View.layout(View.java:17995)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                  at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                                                                                  at android.view.View.layout(View.java:17995)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                  at android.view.View.layout(View.java:17995)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                                  at android.view.View.layout(View.java:17995)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                  at android.view.View.layout(View.java:17995)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                  at android.view.View.layout(View.java:17995)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                  at android.view.View.layout(View.java:17995)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                              	at android
01-24 14:59:40.738 22978-26899/com.latestone.retail_app.uat I/FirebaseCrash: Sending crashes
01-24 14:59:40.738 22978-26899/com.latestone.retail_app.uat I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-24 14:59:40.738 22978-26899/com.latestone.retail_app.uat I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-24 14:59:42.738 22978-26899/com.latestone.retail_app.uat I/FirebaseCrash: Response code: 200
01-24 14:59:42.738 22978-26899/com.latestone.retail_app.uat I/FirebaseCrash: Report sent with crash report id: 18b803bfbc000000

**Comment by msrowley** [comment]
I think your problem is because you changed "*scaleType*".

As mentioned in the README:
**The ScaleType is always CENTER_CROP and you'll get an exception if you try to change it. **This is (currently) by design as it's perfectly fine for profile images.

**Comment by chnouman** [comment]
still getting the same error in kotlin.

 ```
android.view.InflateException: Binary XML file line #0: Error inflating class de.hdodenhof.circleimageview.CircleImageView
                                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                                at com.raywenderlich.galacticon.ExtensionsKt.inflate(Extensions.kt:10)
                                                                                at com.raywenderlich.galacticon.RecyclerAdapter.onCreateViewHolder(RecyclerAdapter.kt:24)
                                                                                at com.raywenderlich.galacticon.RecyclerAdapter.onCreateViewHolder(RecyclerAdapter.kt:13)
                                                                                at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6493)
```

**Comment by hdodenhof** [comment]
Nothing to add here.
