### ISSUE TITLE
Not Working in RemoteViews

### ISSUE THREAD

**Issue by kunwar97** [hdodenhof/CircleImageView#274]
This library is not working for remote views

```
android.app.RemoteServiceException: Bad notification posted from package com.crazyindian.fifafever: Couldn't inflate contentViewsandroid.view.InflateException: Binary XML file line #87: Binary XML file line #87: Error inflating class de.hdodenhof.circleimageview.CircleImageView
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1769)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6499)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:442)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by hdodenhof** [comment]
That's a limitation of `RemoteView`s - they just don't support custom widgets: https://developer.android.com/reference/android/widget/RemoteViews.
