### ISSUE TITLE
android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class de.hdodenhof.circleimageview.CircleImageView

### ISSUE THREAD

**Issue by NarrowOne** [hdodenhof/CircleImageView#285]
Hey, I know this may seem like a repeat of #96 but I've tried all the suggested solutions on that topic and none of them worked. If you could help me it would be much appreciated. Below are the stack trace, gradle file and xml from my project;

**STACK TRACE**
```
08-14 10:11:55.450 6015-6015/com.example.masha.brackloonns E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.masha.brackloonns, PID: 6015
    android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class de.hdodenhof.circleimageview.CircleImageView
        at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.example.masha.brackloonns.StaffAdapter.onCreateViewHolder(StaffAdapter.java:30)
        at com.example.masha.brackloonns.StaffAdapter.onCreateViewHolder(StaffAdapter.java:16)
        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6685)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5869)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1858)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1858)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1171)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
    	at android.view.ViewRootImpl$Traversa
08-14 10:11:55.489 1642-3338/system_process W/ActivityManager:   Force finishing activity com.example.masha.brackloonns/.Staff
08-14 10:11:56.270 1642-1660/system_process W/ActivityManager: Activity pause timeout for ActivityRecord{7d86092 u0 com.example.masha.brackloonns/.Staff t113 f}
08-14 10:12:06.713 1642-1660/system_process W/ActivityManager: Activity destroy timeout for ActivityRecord{7d86092 u0 com.example.masha.brackloonns/.Staff t113 f}
```

**GRADLE**
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.example.masha.brackloonns"
        minSdkVersion 21
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
//        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
} } }

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    //android support
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation "com.android.support:support-core-utils:27.1.1"
    implementation 'com.android.support:design:27.1.1'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.android.support:cardview-v7:27.1.1'
    implementation 'com.android.support:recyclerview-v7:27.1.1'

    testImplementation 'junit:junit:4.12'

//    Other stuff
    implementation 'de.hdodenhof:circleimageview:2.2.0'
    implementation 'com.github.sundeepk:compact-calendar-view:3.0.0'
}
apply plugin: 'com.google.gms.google-services'
```

**XML CODE**
```
<de.hdodenhof.circleimageview.CircleImageView xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/thumb"
        android:layout_width="94dp"
        android:layout_height="94dp"
        android:layout_marginBottom="24dp"
        android:layout_marginStart="20dp"
        android:layout_marginTop="24dp"
        android:src="@drawable/account"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintVertical_bias="0.0" />

    <TextView
        android:id="@+id/job"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginBottom="8dp"
        android:layout_marginEnd="8dp"
        android:layout_marginStart="16dp"
        android:layout_marginTop="24dp"
        android:fontFamily="@font/bevan_regular"
        android:textColor="@android:color/holo_purple"
        android:textSize="18sp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.0"
        app:layout_constraintStart_toEndOf="@+id/thumb"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintVertical_bias="0.0" />

    <TextView
        android:id="@+id/name"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginBottom="8dp"
        android:layout_marginEnd="8dp"
        android:layout_marginStart="16dp"
        android:fontFamily="@font/open_sans_bold"
        android:textColor="@android:color/black"
        android:textSize="14sp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.0"
        app:layout_constraintStart_toEndOf="@+id/thumb"
        app:layout_constraintTop_toBottomOf="@+id/job"
        app:layout_constraintVertical_bias="0.0" />

    <TextView
        android:id="@+id/phone"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginBottom="8dp"
        android:layout_marginEnd="8dp"
        android:layout_marginStart="16dp"
        android:fontFamily="@font/open_sans_semi_bold"
        android:textAllCaps="false"
        android:textColor="@android:color/black"
        android:textSize="12sp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.0"
        app:layout_constraintStart_toEndOf="@+id/thumb"
        app:layout_constraintTop_toBottomOf="@+id/name"
        app:layout_constraintVertical_bias="0.0" />

    <TextView
        android:id="@+id/email"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginBottom="8dp"
        android:layout_marginEnd="8dp"
        android:layout_marginStart="16dp"
        android:fontFamily="@font/open_sans_semi_bold"
        android:textColor="@android:color/black"
        android:textSize="12sp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.0"
        app:layout_constraintStart_toEndOf="@+id/thumb"
        app:layout_constraintTop_toBottomOf="@+id/phone"
        app:layout_constraintVertical_bias="0.002" />
```

**Comment by NarrowOne** [comment]
This issue only arose after updating to Android Studio 3.1.4 btw

**Comment by hdodenhof** [comment]
The most interesting bits of the stack trace are cut off - can you try to get a full one?

**Comment by NarrowOne** [comment]
sorry, first time reporting an issue so I'm not sure which parts of stack trace are important to you heres it is in full;

```
 --------- beginning of main
08-15 10:08:16.401 1232-2075/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 1019904
08-15 10:08:16.406 1232-1232/? E/EGL_emulation: tid 1232: eglCreateSyncKHR(1881): error 0x3004 (EGL_BAD_ATTRIBUTE)
08-15 10:08:16.437 1336-1645/? D/AudioFlinger: mixer(0xb4300000) throttle end: throttle time(11)
08-15 10:08:16.534 1232-1616/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8294400
08-15 10:08:16.763 5450-5497/com.example.masha.brackloonns D/EGL_emulation: eglMakeCurrent: 0xae3e4900: ver 3 0 (tinfo 0xae3d2a00)
08-15 10:08:16.852 5450-5450/com.example.masha.brackloonns D/CustomAdapter: onCreateViewHolder: called.
08-15 10:08:16.863 5450-5450/com.example.masha.brackloonns D/AndroidRuntime: Shutting down VM


    --------- beginning of crash
08-15 10:08:16.901 5450-5450/com.example.masha.brackloonns E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.masha.brackloonns, PID: 5450
    android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class de.hdodenhof.circleimageview.CircleImageView
        at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.example.masha.brackloonns.StaffAdapter.onCreateViewHolder(StaffAdapter.java:30)
        at com.example.masha.brackloonns.StaffAdapter.onCreateViewHolder(StaffAdapter.java:16)
        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6685)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5869)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1858)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1858)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1171)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
    	at android.view.ViewRootImpl$Traversa
08-15 10:08:17.117 1336-1644/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 2347885 , only wrote 2346550
    Not supplying enough data to HAL, expected position 2346555 , only wrote 2346550
08-15 10:08:17.143 1336-1644/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 2347704 , only wrote 2347211
08-15 10:08:17.146 1986-3877/system_process W/ActivityManager:   Force finishing activity com.example.masha.brackloonns/.Staff
08-15 10:08:17.220 1232-1292/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 1019904
08-15 10:08:17.259 1232-1232/? E/EGL_emulation: tid 1232: eglCreateSyncKHR(1881): error 0x3004 (EGL_BAD_ATTRIBUTE)
08-15 10:08:17.307 1232-1292/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
08-15 10:08:17.307 1986-5518/system_process D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
08-15 10:08:17.355 1336-1644/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 2356547 , only wrote 2356465
    Not supplying enough data to HAL, expected position 2356470 , only wrote 2356465
08-15 10:08:17.422 1336-1644/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 2359402 , only wrote 2357126
08-15 10:08:17.477 1336-1644/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 2359542 , only wrote 2358448
08-15 10:08:17.567 1336-1644/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 2362439 , only wrote 2361753
    Not supplying enough data to HAL, expected position 2361757 , only wrote 2361753
08-15 10:08:17.614 1336-1644/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 2363835 , only wrote 2362414
08-15 10:08:17.702 1336-1644/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 2366296 , only wrote 2365719
08-15 10:08:17.703 1336-1644/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 2365723 , only wrote 2365719
08-15 10:08:17.726 1336-1644/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 2366762 , only wrote 2366380
08-15 10:08:17.736 3404-3425/com.google.android.gms W/art: Long monitor contention event with owner method=boolean nfm.a(nfl, android.content.ServiceConnection, java.lang.String) from :com.google.android.gms@12521024@12.5.21 (040700-189987672):6 waiters=0 for 165ms
08-15 10:08:17.783 1336-1644/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 2368888 , only wrote 2367702
08-15 10:08:17.783 1986-2043/system_process W/ActivityManager: Activity pause timeout for ActivityRecord{8edc0cf u0 com.example.masha.brackloonns/.Staff t138 f}
08-15 10:08:17.879 1336-1644/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 2371937 , only wrote 2371668
    Not supplying enough data to HAL, expected position 2371677 , only wrote 2371668
08-15 10:08:17.891 1986-5518/system_process I/OpenGLRenderer: Initialized EGL, version 1.4
08-15 10:08:17.905 1986-5518/system_process D/EGL_emulation: eglCreateContext: 0xa0c02240: maj 3 min 0 rcv 3
08-15 10:08:17.918 3404-3425/com.google.android.gms W/art: Long monitor contention event with owner method=boolean nfm.a(nfl, android.content.ServiceConnection, java.lang.String) from :com.google.android.gms@12521024@12.5.21 (040700-189987672):6 waiters=0 for 181ms
08-15 10:08:17.932 1986-5518/system_process D/EGL_emulation: eglMakeCurrent: 0xa0c02240: ver 3 0 (tinfo 0x9ef23380)
08-15 10:08:17.952 1986-5518/system_process E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
    glUtilsParamSize: unknow param 0x00008824
08-15 10:08:18.019 1336-1644/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
08-15 10:08:18.020 1986-2010/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
08-15 10:08:18.031 1336-1644/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
08-15 10:08:18.031 1986-5518/system_process D/EGL_emulation: eglMakeCurrent: 0xa0c02240: ver 3 0 (tinfo 0x9ef23380)
08-15 10:08:18.077 1986-2048/system_process I/Choreographer: Skipped 45 frames!  The application may be doing too much work on its main thread.
08-15 10:08:18.120 1336-1644/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 2382303 , only wrote 2382244
08-15 10:08:18.197 1336-1644/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
    Not supplying enough data to HAL, expected position 2385621 , only wrote 2384888
    Not supplying enough data to HAL, expected position 2384891 , only wrote 2384888
08-15 10:08:18.215 1336-1644/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 2385664 , only wrote 2385549
08-15 10:08:18.216 2822-3107/com.android.launcher3 D/EGL_emulation: eglMakeCurrent: 0xae3e4600: ver 3 0 (tinfo 0xae3d2720)
08-15 10:08:18.293 1336-1644/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 2388977 , only wrote 2388193
    Not supplying enough data to HAL, expected position 2388196 , only wrote 2388193
08-15 10:08:18.367 1336-1644/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
08-15 10:08:18.399 1336-1644/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 2392893 , only wrote 2392159
    Hardware backing HAL too slow, could only write 0 of 661 frames
08-15 10:08:18.481 1336-1644/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
08-15 10:08:18.564 1336-1644/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 2399415 , only wrote 2398769
    Not supplying enough data to HAL, expected position 2398772 , only wrote 2398769
08-15 10:08:18.581 1336-1644/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 2399531 , only wrote 2399430
08-15 10:08:18.618 1336-1644/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
08-15 10:08:18.867 1986-2048/system_process I/Choreographer: Skipped 43 frames!  The application may be doing too much work on its main thread.
08-15 10:08:18.972 2822-3107/com.android.launcher3 W/OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
    Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
08-15 10:08:19.106 1986-2043/system_process I/ActivityManager: Killing 3297:com.google.android.apps.maps/u0a39 (adj 15): empty #17
08-15 10:08:19.529 1336-1645/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 2482009 , only wrote 2441073
08-15 10:08:28.630 1986-2043/system_process W/ActivityManager: Activity destroy timeout for ActivityRecord{8edc0cf u0 com.example.masha.brackloonns/.Staff t138 f}
08-15 10:08:29.178 1986-2043/system_process W/ActivityManager: Activity destroy timeout for ActivityRecord{6e79b32 u0 com.example.masha.brackloonns/.NewsFeed t138 f}
08-15 10:09:00.102 1232-1306/? D/hwcomposer: hw_composer sent 165 syncs in 60s

```

**Comment by hdodenhof** [comment]
Closing as stale. Please re-open with a full stack trace if this is still an issue.
