### ISSUE TITLE
Error while load CircleImageView on Android 4

### ISSUE THREAD

**Issue by prsolucoes** [hdodenhof/CircleImageView#287]
Hi,

Im getting the error on Android 4:

```
6 20:35:02.772 20727-20727/br.com.ubook.ubooktim W/dalvikvm: Unable to resolve superclass of Lde/hdodenhof/circleimageview/CircleImageView$OutlineProvider; (272)
    Link of class 'Lde/hdodenhof/circleimageview/CircleImageView$OutlineProvider;' failed
08-16 20:35:02.782 20727-20727/br.com.ubook.ubooktim E/dalvikvm: Could not find class 'de.hdodenhof.circleimageview.CircleImageView$OutlineProvider', referenced from method de.hdodenhof.circleimageview.CircleImageView.init
08-16 20:35:02.782 20727-20727/br.com.ubook.ubooktim W/dalvikvm: VFY: unable to resolve new-instance 2338 (Lde/hdodenhof/circleimageview/CircleImageView$OutlineProvider;) in Lde/hdodenhof/circleimageview/CircleImageView;
08-16 20:35:02.782 20727-20727/br.com.ubook.ubooktim D/dalvikvm: VFY: replacing opcode 0x22 at 0x000e
08-16 20:35:02.802 20727-20727/br.com.ubook.ubooktim W/dalvikvm: Unable to resolve superclass of Lde/hdodenhof/circleimageview/CircleImageView$OutlineProvider; (272)
    Link of class 'Lde/hdodenhof/circleimageview/CircleImageView$OutlineProvider;' failed
08-16 20:35:02.802 20727-20727/br.com.ubook.ubooktim D/dalvikvm: DexOpt: unable to opt direct call 0x3186 at 0x11 in Lde/hdodenhof/circleimageview/CircleImageView;.init
08-16 20:35:02.962 20727-20797/br.com.ubook.ubooktim D/FA: Logging event (FE): user_engagement(_e), Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=7043, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=7834691520531409482}]
08-16 20:35:03.012 20727-20727/br.com.ubook.ubooktim D/AndroidRuntime: Shutting down VM
08-16 20:35:03.012 20727-20727/br.com.ubook.ubooktim W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4194fda0)
08-16 20:35:03.012 20727-20727/br.com.ubook.ubooktim W/System.err: android.view.InflateException: Binary XML file line #135: Error inflating class Button
08-16 20:35:03.022 20727-20727/br.com.ubook.ubooktim W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:719)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
08-16 20:35:03.032 20727-20727/br.com.ubook.ubooktim W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
08-16 20:35:03.042 20727-20727/br.com.ubook.ubooktim W/System.err:     at br.com.ubook.ubookapp.ui.fragment.BaseFragment.onCreateView(BaseFragment.java:59)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
```

**Comment by prsolucoes** [comment]
My XML

```
<de.hdodenhof.circleimageview.CircleImageView
                    android:id="@+id/ivProfile"
                    android:layout_width="90dp"
                    android:layout_height="90dp"
                    android:layout_alignParentTop="true"
                    android:layout_centerHorizontal="true"
                    android:layout_marginTop="20dp"
                    android:scaleType="centerCrop"
                    app:civ_border_width="0dp"
                    app:srcCompat="@drawable/profile_placeholder" />
```

**Comment by prsolucoes** [comment]
I change to PNG images, but same problem happen:

```
<de.hdodenhof.circleimageview.CircleImageView
                    android:id="@+id/ivProfile"
                    android:layout_width="90dp"
                    android:layout_height="90dp"
                    android:layout_alignParentTop="true"
                    android:layout_centerHorizontal="true"
                    android:layout_marginTop="20dp"
                    android:scaleType="centerCrop"
                    app:civ_border_width="0dp"
                    android:src="@drawable/ic_profile_placeholder" />

```

**Comment by hdodenhof** [comment]
The crash is not caused by `CircleImageView`. The messages you are seeing about `CircleImageView$OutlineProvider` are expected on Android 4 and do not cause any harm.

The problem is with the button in your layout:
`android.view.InflateException: Binary XML file line #135: Error inflating class Button`.

**Comment by prsolucoes** [comment]
Hi,

Yes, i correct it. Something inside the drawable is incompatible with Android 4, but not on Android 5 or more.  -,-

Now, it is working. But i can use "app:srcCompat" instead of the PNG?

**Comment by hdodenhof** [comment]
`srcCompat` won't work. Are you trying to display a vector image? If so, please have a look at the FAQ section of the README and [older issues asking for this](https://github.com/hdodenhof/CircleImageView/search?q=vector&type=Issues).

**Comment by prsolucoes** [comment]
I already read it. But today it is running OK from android 4 to 8 with srcCompat. 
Whats the really problem?

**Comment by hdodenhof** [comment]
I'm sorry, but I don't understand your question. You're original issue was not related to this library and usage of `srcCompat` has been clarified. What problem are you looking to get an answer to?

**Comment by prsolucoes** [comment]
The original problem was solved. Is a invalid drawable that only throw error on Android 4. Im only asking now about srcCompat, it is working with vector without problem. I want understand what the problem with srcCompat and your library.

Thanks.

**Comment by hdodenhof** [comment]
Using `app:srcCompat` with a `CircleImageView` just shouldn't do anything, it's value not evaluated at all.
