### ISSUE TITLE
AppCompatImageView cannot be cast

### ISSUE THREAD

**Issue by mohamedagamy** [hdodenhof/CircleImageView#291]
```
09-03 16:50:17.609 15363-15363/com.smartkiz.driveme.enduser E/UncaughtException: java.lang.ClassCastException: android.support.v7.widget.AppCompatImageView cannot be cast to de.hdodenhof.circleimageview.CircleImageView
        at com.smartkiz.driveme.enduser.ui.fragment.drawer.ProfileFrament.onCreateView(ProfileFrament.java:112)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5019)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by hdodenhof** [comment]
You are trying to cast a `CircleImageView` to an `AppCompatImageVieẁ` - that can't work and is not an issue with this library.
