### ISSUE TITLE
Android P crash: "Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed"

### ISSUE THREAD

**Issue by factor-lab** [hdodenhof/CircleImageView#363]
It seems there is a crash only in Android 10:
```
Fatal Exception: java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
       at android.graphics.Canvas.checkValidClipOp(Canvas.java:853)
       at android.graphics.Canvas.clipPath(Canvas.java:1081)
       at com.theartofdev.edmodo.cropper.CropOverlayView.drawBackground(CropOverlayView.java:707)
       at com.theartofdev.edmodo.cropper.CropOverlayView.onDraw(CropOverlayView.java:649)
       at android.view.View.draw(View.java:21594)
       at android.view.View.updateDisplayListIfDirty(View.java:20471)
       at android.view.View.draw(View.java:21326)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4413)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4174)
       at android.view.View.updateDisplayListIfDirty(View.java:20462)
       at android.view.View.draw(View.java:21326)
...
```

**Comment by hdodenhof** [comment]
The crash happens in `com.theartofdev.edmodo.cropper.CropOverlayView` and that's not part of this library. You should head over to the [Edmodo Cropper repo](https://github.com/edmodo/cropper) for help.

**Comment by factor-lab** [comment]
Thank you! Sorry, I misread the logs.
