### ISSUE TITLE
Loading isse

### ISSUE THREAD

**Issue by JagadishaIncture** [hdodenhof/CircleImageView#375]
android.view.InflateException: Binary XML file line #133: Binary XML file line #133: Error inflating class <unknown>
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)

**Comment by hdodenhof** [comment]
Please post the full stack trace - you left out the relevant parts.

**Comment by JagadishaIncture** [comment]
Caused by: android.view.InflateException: Binary XML file line #59: Binary XML file line #59: Error inflating class de.hdodenhof.circleimageview.CircleImageView

**Comment by hdodenhof** [comment]
You are using an unsupported scale type. From the readme:
> The ScaleType is always CENTER_CROP and you'll get an exception if you try to change it. This is (currently) by design as it's perfectly fine for profile images.
