### ISSUE TITLE
Width and height must be > 0 when using CircularProgressDrawable

### ISSUE THREAD

**Issue by egeysn** [hdodenhof/CircleImageView#426]
` CircularProgressDrawable progress = new CircularProgressDrawable(context);
        progress.setColorSchemeColors(R.color.colorPrimary, R.color.colorPrimaryDark, R.color.colorAccent);
        progress.setCenterRadius(30f);
        progress.setStrokeWidth(5f);
        progress.start();`

`   Glide.with(context)
                    .load(url)
                    .dontAnimate()
                    .error(R.color.color_secondary_10)
                    .placeholder(progress)
                    .into(view);`

Hi, when i use CircularProgressDrawable with Glide , I get the following error ,can someone help me? (Also, I did not encounter this problem in other image views.)

> W/System.err: java.lang.IllegalArgumentException: width and height must be > 0
W/System.err:     at android.graphics.Bitmap.createBitmap(Bitmap.java:1150)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1117)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1067)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1028)
        at de.hdodenhof.circleimageview.CircleImageView.getBitmapFromDrawable(CircleImageView.java:318)
        at de.hdodenhof.circleimageview.CircleImageView.initializeBitmap(CircleImageView.java:335)
        at de.hdodenhof.circleimageview.CircleImageView.setImageDrawable(CircleImageView.java:263)
        at com.bumptech.glide.request.target.ImageViewTarget.setDrawable(ImageViewTarget.java:53)
        at com.bumptech.glide.request.target.ImageViewTarget.onLoadStarted(ImageViewTarget.java:66)
        at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:258)
      

>

**Comment by hdodenhof** [comment]
Closing this as it's certainly obsolete by now - sorry, was quite inactive here for a while.
